### ISSUE TITLE
Create new release with #20

### ISSUE THREAD

**Issue by sirhcel** [Sensirion/sensirion-i2c-rs#22]
* My work on a driver for the SHT4x sensors (https://github.com/sirhcel/sht4x) seems to come into a state for releasing it
* It depends on #20 which is still unreleased
* Could you please create and publish a new release of the _sensirion-i2c_ crate?

**Comment by psachs** [comment]
there is a new release v0.2.0 available: https://crates.io/crates/sensirion-i2c
