### ISSUE TITLE
Crate docs

### ISSUE THREAD

**Issue by dbrgn** [Sensirion/sensirion-i2c-rs#9]
The documentation looks a bit... thin right now :slightly_smiling_face: 

![2020-08-24-174642_1303x538_scrot](https://user-images.githubusercontent.com/105168/91066245-c7e9dd80-e631-11ea-9f0e-a1ad21fcbcbb.png)

Adding some docs (explaining how the crate is meant to be used and what the functions do) would definitely improve things!

**Comment by dbrgn** [comment]
(You might even want to add `#![deny(missing_docs)]` to the crate attributes.)

**Comment by rnestler** [comment]
Is there a way to avoid duplicating documentation in the `README.md` and `lib.rs`?

**Comment by rnestler** [comment]
Oh there is https://github.com/rust-lang/rust/issues/44732 which describes exactly this use case :slightly_smiling_face:
